# Generated by Django 2.2.11 on 2020-04-13 10:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deadhang_endurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 4, 13, 10, 48, 37, 173033, tzinfo=utc))),
                ('hand_position', models.CharField(choices=[('HG', 'Half Grimp'), ('OH', 'Open Hand')], default='HG', max_length=2)),
                ('hold_duration', models.CharField(choices=[('1', 'Short'), ('2', 'Long')], max_length=1)),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('crimp_size', models.IntegerField(default=20)),
                ('level', models.CharField(max_length=1)),
                ('sets', models.IntegerField(default=4)),
                ('repetitions', models.IntegerField(default=6)),
                ('session_counter', models.IntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Deadhangs Endurance',
            },
        ),
        migrations.CreateModel(
            name='Deadhang_max',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 4, 13, 10, 48, 37, 172626, tzinfo=utc))),
                ('hand_position', models.CharField(choices=[('HG', 'Half Grimp'), ('OH', 'Open Hand')], default='HG', max_length=2)),
                ('hands', models.CharField(choices=[('OH', 'One Hand'), ('TH', 'Two Hands')], default='TH', max_length=2)),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('crimp_size', models.IntegerField(default=20)),
                ('session_counter', models.IntegerField(blank=True, null=True)),
                ('sets', models.IntegerField(default=5)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Deadhangs Max',
            },
        ),
        migrations.CreateModel(
            name='Pullup_endurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 4, 13, 10, 48, 37, 173827, tzinfo=utc))),
                ('session_counter', models.IntegerField()),
                ('sets', models.IntegerField(default=20)),
                ('repetitions', models.IntegerField(default=5)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Pullups Endurance',
            },
        ),
        migrations.CreateModel(
            name='Pullup_max',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 4, 13, 10, 48, 37, 173498, tzinfo=utc))),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('session_counter', models.IntegerField()),
                ('sets', models.IntegerField(default=3)),
                ('repetitions', models.IntegerField(default=3)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Pullups Max',
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('d1', 'Deadhang Maximum Strength'), ('d2', 'Deadhang Strength-Endurance'), ('p1', 'Pullups Maximum Strength'), ('p2', 'Pullups Strength-Endurance')], max_length=2)),
                ('date', models.DateField(blank=True)),
            ],
        ),
    ]
