# Generated by Django 2.2.11 on 2020-12-30 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('d1', 'Deadhang Maximum Strength'), ('d2', 'Deadhang Strength-Endurance'), ('p1', 'Pullups Maximum Strength'), ('p2', 'Pullups Strength-Endurance'), ('c', 'Custom Training')], max_length=2)),
                ('date', models.DateField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pullup_max',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('additional_weight', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('body_weight', models.DecimalField(decimal_places=2, default=72, max_digits=5)),
                ('session_counter', models.IntegerField()),
                ('sets', models.IntegerField(default=3)),
                ('repetitions', models.IntegerField(default=3)),
                ('comment', models.TextField(blank=True, null=True)),
                ('training', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_pmax', to='trainingdata.Training')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Pullups Max',
            },
        ),
        migrations.CreateModel(
            name='Pullup_endurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('session_counter', models.IntegerField()),
                ('sets', models.IntegerField(default=20)),
                ('repetitions', models.IntegerField(default=5)),
                ('comment', models.TextField(blank=True, null=True)),
                ('training', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_pend', to='trainingdata.Training')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Pullups Endurance',
            },
        ),
        migrations.CreateModel(
            name='Deadhang_max',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('hand_position', models.CharField(choices=[('HG', 'Half Grimp'), ('OH', 'Open Hand')], default='HG', max_length=2)),
                ('hands', models.CharField(choices=[('OH', 'One Hand'), ('TH', 'Two Hands')], default='TH', max_length=2)),
                ('additional_weight', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('body_weight', models.DecimalField(decimal_places=2, default=72, max_digits=5)),
                ('relative_strength', models.IntegerField(default=100)),
                ('crimp_size', models.IntegerField(default=20)),
                ('session_counter', models.IntegerField(blank=True, null=True)),
                ('sets', models.IntegerField(default=5)),
                ('comment', models.TextField(blank=True, null=True)),
                ('training', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_dmax', to='trainingdata.Training')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadhang_max', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Deadhangs Max',
            },
        ),
        migrations.CreateModel(
            name='Deadhang_endurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('hand_position', models.CharField(choices=[('HG', 'Half Grimp'), ('OH', 'Open Hand')], default='HG', max_length=2)),
                ('hold_duration', models.CharField(choices=[('1', 'Short'), ('2', 'Long')], default='1', max_length=1)),
                ('additional_weight', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('body_weight', models.DecimalField(decimal_places=2, default=72, max_digits=5)),
                ('crimp_size', models.IntegerField(default=20)),
                ('level', models.CharField(max_length=1)),
                ('sets', models.IntegerField(default=4)),
                ('repetitions', models.IntegerField(default=6)),
                ('session_counter', models.IntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('training', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_dend', to='trainingdata.Training')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Deadhangs Endurance',
            },
        ),
        migrations.CreateModel(
            name='CustomSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('energy_system', models.CharField(choices=[('1', 'Maximum Strength (anaerobic alactic)'), ('2', 'Strength-Endurance (glycolytic/anaerobic lactic)'), ('3', 'Aerobic Endurance (aerobic/oxidative)'), ('0', 'None')], default='1', max_length=1)),
                ('target', models.CharField(choices=[('1', 'Fingers'), ('2', 'Upper Body'), ('3', 'Core'), ('4', 'Flexibility'), ('5', 'Antagonists'), ('6', 'Other')], default='1', max_length=1)),
                ('repetitions', models.IntegerField(blank=True, null=True)),
                ('on_off_time', models.CharField(blank=True, max_length=15, null=True)),
                ('sets', models.IntegerField(blank=True, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('crimp_size', models.IntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('training', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_training', to='trainingdata.Training')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_training', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
