# Generated by Django 2.2.11 on 2020-04-13 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trainingdata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pullup_max',
            name='training',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_pmax', to='trainingdata.Training'),
        ),
        migrations.AddField(
            model_name='pullup_max',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pullup_endurance',
            name='training',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_pend', to='trainingdata.Training'),
        ),
        migrations.AddField(
            model_name='pullup_endurance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deadhang_max',
            name='training',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_dmax', to='trainingdata.Training'),
        ),
        migrations.AddField(
            model_name='deadhang_max',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadhang_max', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deadhang_endurance',
            name='training',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_dend', to='trainingdata.Training'),
        ),
        migrations.AddField(
            model_name='deadhang_endurance',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
