# Generated by Django 2.2.11 on 2020-04-15 19:22

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trainingdata', '0002_auto_20200413_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deadhang_endurance',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 15, 19, 22, 46, 486532, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='deadhang_endurance',
            name='hold_duration',
            field=models.CharField(choices=[('1', 'Short'), ('2', 'Long')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='deadhang_max',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 15, 19, 22, 46, 486090, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pullup_endurance',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 15, 19, 22, 46, 487282, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pullup_max',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 15, 19, 22, 46, 486940, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='training',
            name='title',
            field=models.CharField(choices=[('d1', 'Deadhang Maximum Strength'), ('d2', 'Deadhang Strength-Endurance'), ('p1', 'Pullups Maximum Strength'), ('p2', 'Pullups Strength-Endurance'), ('c', 'Custom Training')], max_length=2),
        ),
        migrations.CreateModel(
            name='CustomSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 4, 15, 19, 22, 46, 485665, tzinfo=utc))),
                ('energy_system', models.CharField(choices=[('1', 'Maximum Strength (anaerobic alactic)'), ('2', 'Strength-Endurance (glycolytic/anaerobic lactic)'), ('3', 'Aerobic Endurance (aerobic/oxidative)')], default='1', max_length=1)),
                ('target', models.CharField(choices=[('1', 'Fingers'), ('2', 'Upper Body'), ('3', 'Core'), ('4', 'Flexibility'), ('5', 'Antagonists')], default='1', max_length=1)),
                ('repetitions', models.IntegerField(blank=True, default=6, null=True)),
                ('on_off_time', models.CharField(blank=True, max_length=15, null=True)),
                ('sets', models.IntegerField(blank=True, default=4, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('crimp_size', models.IntegerField(blank=True, default=20, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('training', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_training', to='trainingdata.Training')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_training', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
