# Generated by Django 2.2.11 on 2020-04-15 20:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trainingdata', '0004_auto_20200415_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customsession',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 15, 20, 4, 50, 104416, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customsession',
            name='repetitions',
            field=models.IntegerField(blank=True, default=6, null=True),
        ),
        migrations.AlterField(
            model_name='customsession',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='deadhang_endurance',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 15, 20, 4, 50, 105292, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='deadhang_max',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 15, 20, 4, 50, 104844, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pullup_endurance',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 15, 20, 4, 50, 106028, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pullup_max',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 15, 20, 4, 50, 105693, tzinfo=utc)),
        ),
    ]
