# Generated by Django 2.2.11 on 2020-04-19 09:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trainingdata', '0007_auto_20200419_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customsession',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 19, 9, 17, 54, 890165, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='deadhang_endurance',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 19, 9, 17, 54, 898359, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='deadhang_max',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 19, 9, 17, 54, 894391, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pullup_endurance',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 19, 9, 17, 54, 906626, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pullup_max',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 19, 9, 17, 54, 903159, tzinfo=utc)),
        ),
    ]
